sudo: required
dist: trusty
language: node_js
node_js:
  - node
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
services:
  - postgresql
before_script:
  - psql -c 'drop database if exists document_test;' -U postgres
  - psql -c 'drop database if exists document_mgmt;' -U postgres
  - psql -c 'create database document_test;' -U postgres
  - psql -c 'create database if exists document_mgmt;' -U postgres
  - NODE_ENV=test npm run migration
script:
  - NODE_ENV=test npm test
after_success:
  - NODE_ENV=test npm run coveralls
addons:
  postgresql: "9.3"
after_failure:
  - npm run coveralls